services:
  database:
    container_name: ecoo-database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoo_db
    ports:
      - "5432:5432"
    profiles: ["development", "deploy"]

  cache:
    container_name: ecoo-cache
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    profiles: ["development", "deploy"]

  smtp:
    container_name: ecoo-smtp
    image: rnwood/smtp4dev:v3
    ports:
      - "3010:80"
      - "2525:25"
    profiles: ["development"]
    logging:
      driver: "none"

  server: &server
    container_name: ecoo-server
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    restart: always
    profiles: ["deploy"]

  development-server:
    <<: *server
    depends_on:
      - smtp
      - cache
      - database
    profiles: ["development"]

volumes:
  redis:
    driver: local
