services:
  database:
    container_name: ecoo-database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoo_db
    ports:
      - "5432:5432"
    profiles: ["development", "deploy"]

  cache:
    container_name: ecoo-cache
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-cache:/data
    profiles: ["development", "deploy"]

  smtp:
    container_name: ecoo-smtp
    image: rnwood/smtp4dev:v3
    ports:
      - "3010:80"
      - "2525:25"
    profiles: ["development"]
    logging:
      driver: "none"

  tasks:
    container_name: ecoo-tasks
    image: redis:7-alpine
    volumes:
      - redis-tasks:/data
    profiles: ["development", "deploy"]
    ports:
      - "6380:6379"

  server: &server
    container_name: ecoo-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/app/src
      - storage:/storage
    depends_on:
      - database
      - cache
    profiles: ["deploy"]
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  development-server:
    <<: *server
    network_mode: "host"
    depends_on:
      - smtp
    profiles: ["development"]

volumes:
  redis-cache:
    driver: local
  redis-tasks:
    driver: local
  storage:
    driver: local
