-- AlterTable
ALTER TABLE "offers" ADD COLUMN     "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "closes_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "recurring" BOOLEAN NOT NULL DEFAULT false;
