name: run deploy

on:
  push:
    branches:
      - main

jobs:
  run-deploy:
    name: Deploy workflow
    runs-on: self-hosted
    steps:
      - name: Deploy application
        run: |
          cd /deploy/rest-api

          sudo docker-compose stop

          sudo docker rm ecoo-server || true

          sudo git pull

          sudo pnpm run deploy:build

          sudo npx prisma migrate deploy
