name: run deploy production

on:
  push:
    branches:
      - main

jobs:
  run-deploy:
    name: Deploy workflow production
    runs-on: self-hosted
    steps:
      - name: Deploy application to production
        run: |
          sudo su - << 'EOF'

          cd /deploy/rest-api

          docker-compose stop

          docker rm ecoo-server || true

          git pull

          pnpm run deploy:build

          npx prisma migrate deploy

          EOF
