name: run production deploy

on:
  push:
    branches:
      - main

jobs:
  run-deploy-production:
    name: Production deploy workflow
    runs-on: ecoo-producao
    steps:
      - name: Deploy application to production
        run: |
          sudo su - << 'EOF'

          cd /deploy/rest-api

          docker-compose stop

          docker rm ecoo-server || true

          git pull

          pnpm run deploy:build

          npx prisma migrate deploy

          EOF
