name: run staging deploy

on:
  push:
    branches:
      - staging

jobs:
  run-deploy-staging:
    name: Staging deploy workflow
    runs-on: ecoo-homologacao
    steps:
      - name: Deploy application to staging
        run: |
          sudo su - << 'EOF'

          cd /deploy/rest-api

          docker-compose stop

          docker rm ecoo-server || true

          git pull

          pnpm run deploy:build

          npx prisma migrate deploy

          EOF
