name: run deploy

on:
  push:
    branches:
      - main

jobs:
  run-deploy:
    name: Deploy workflow
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          cd /deploy/rest-api

          docker ps -q | xargs -r docker stop

          docker rm -f ecoo-server || true

          git pull origin main

          pnpm run deploy:build
          npx prisma migrate deploy
