name: run unit tests

on:
  - pull_request

jobs:
  run-unit-tests:
    name: Unit tests workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Setup dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm run test
        env:
          ENVIRONMENT: TEST
          SERVER_PORT: 3333
          SERVER_URL: http://localhost:3333
          JWT_SECRET: UNIT_TESTS
          APP_URL: http://localhost:3000
          WS_URL: ws://localhost:8080/messages
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ecoo_db?schema=public
          CACHE_URL: redis://localhost:6379
          STORAGE_URL: ubuntu/ecoo/rest-api/src/test/storage/temp
          INTEGRATIONS_AUTHORIZATION: UNIT_TESTS
          EMAIL_ACCOUNT: suporte@ecoo.org.br
          EMAIL_PASSWORD: senha
          SMTP_HOST: localhost
          SMTP_PORT: 2525
          BATCH_SMTP_HOST: localhost
          BATCH_SMTP_PORT: 2525
          WAREHOUSE_NAME: Armazém do eCOO
