name: run deploy

on:
  push:
    branches:
      - main

jobs:
  run-deploy:
    name: Deploy workflow
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          sudo su

          cd /deploy/rest-api

          docker-compose stop

          docker rm ecoo-server || true

          git pull

          pnpm run deploy:build

          npx prisma migrate deploy
